# Generated by Django 2.2.1 on 2019-05-23 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='junpyth',
            old_name='progress',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='junpyth',
            name='results',
        ),
        migrations.AddField(
            model_name='junpyth',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date to publish'),
            preserve_default=False,
        ),
    ]
