# Generated by Django 2.2.1 on 2019-05-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190523_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junpyth',
            name='url',
            field=models.URLField(),
        ),
    ]
