# Generated by Django 2.2.1 on 2019-06-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20190528_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Junpyth',
            new_name='Site',
        ),
    ]
