# Generated by Django 2.2.1 on 2019-06-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20190622_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='Site2pars',
        ),
    ]
